# Generated by Django 3.0.8 on 2020-07-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='', help_text='enter title of blog', max_length=50),
        ),
    ]
